spring:
  application:
    name: ExpedNow
  data:
    mongodb:
      uri: mongodb://localhost:27017/expednow
  mail:
    enabled: true
    host: smtp.gmail.com
    port: 587
    username: lamiahaded99@gmail.com # Replace with your actual Gmail
    password: zznu ywvs nvdc miso     # Generate App Password from Gmail settings
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  # Rest of your configuration...
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 382950926394-djonps75gpc1165601eqq237hs954ko4.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: http://localhost:4200/oauth2/callback
          facebook:
            client-id: YOUR_FACEBOOK_CLIENT_ID
            client-secret: YOUR_FACEBOOK_CLIENT_SECRET
            scope:
              - email
              - public_profile
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
  main:
    allow-circular-references: true
  profiles:
    active: dev

stripe:
  api-key: ${STRIPE_SECRET_KEY:}  # Fallback to .env if not set here
  publishable-key: ${STRIPE_PUBLISHABLE_KEY:}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET:}
  currency: usd

app:
  frontend:
    url: http://localhost:4200

jwt:
  secret: hzIOh5KpmuK48srRGTg3ip+5dqRxzCkyWTu0PxOfMGI=
  expirationMs: 86400000
  refreshExpirationMs: 604800000

file:
  upload-dir: C:\\pfe4\\uploads

pricing:
  base: 5.0
  distance-rate: 0.8
  weight-rate: 0.5
  urgency-fee: 3.0
  peak-surcharge: 0.2
  holiday-surcharge: 0.3
  rules:
    rule1: distance > 10 && weight > 5

google:
  maps:
    api:
      key: AIzaSyDsywwThSj5QgW0PiooUwr_QCKW15Fm2PE
    distance-matrix:
      url: https://maps.googleapis.com/maps/api/distancematrix/json
    geocoding:
      url: https://maps.googleapis.com/maps/api/geocode/json

logging:
  level:
    org:
      springframework:
        mail: DEBUG
        data:
          convert:
            CustomConversions: ERROR
        security:
          config:
            annotation:
              authentication:
                configuration:
                  InitializeUserDetailsBeanManagerConfigurer: ERROR
        web:
          socket: DEBUG
        messaging:
          simp: DEBUG
      eclipse:
        angus:
          mail: DEBUG

mvn:
  spring-boot:
    run:
      profiles: debug